name: handshape
channels:
- conda-forge
- defaults
dependencies:
  - python=3.6
  - numpy=1.13.1
  - scipy=0.19.1
  - jinja2=2.9.6
  - pygmo=2.7
  - pathos=0.2.1
  - cython=0.28.2
  - six=1.11.0
  - psutil=5.4.5
  - scikit-learn=0.19.0
  - typing=3.6.4
  - sphinx=1.7.4
  - sphinx_rtd_theme=0.3.1
  - joblib=0.11
  - docutils=0.14
  - setuptools=39.2.0
  - pip:
    - pyclipper==1.1.0
    - ../smac/random_forest_run/build/python_package/dist/pyrfr-0.8.0-cp36-cp36m-win_amd64.whl
    - smac==0.8.0
    - configspace==0.4.6